name: Alexander
favicon: null
layout_spectrum: 0.10253713210113347
typography_spectrum: 0.6756975976750255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0e0f'
    - '#272725'
    - '#fefefc'
    - '#434037'
    - '#61553f'
  brandStrength: 0.918517557438463
  lightness: 0.47344625391997397
  saturation: 0.7252681409008801
  rhythmicContrast: 0.7115010377019644
purpose: []
